export const ROUTES = {
  home: "/",
  dashboard: "/dashboard",
  arizalar: "/arizalar",
  groups: "/groups",
  courses: "/courses",
  news: "/news",
  adminSettings: "adminSettings",
  teacherSettings: "teacherSettings",
  subjects: "/subjects",
  finals: "/finals",
  login: "/login",
  retake: "/retake",
  table: "/table",
  plan: "/plan",
} as const;
