export const ROUTES = {
  home: "/",
  adminDashboard: "/admin/",
  adminApplications: "/admin/applications",
  // dashboard: "/dashboard",
  // applications: "/applications",
  adminGroups: "/admin/groups",
  adminCourses: "/admin/courses",
  adminNews: "/admin/news",
  adminSettings: "/admin/adminSettings",
  teacherSettings: "/admin/teacherSettings",
  studentSettings: "/admin/studentSettings",
  subjects: "/subjects",
  finals: "/finals",
  login: "/login",
  retake: "/retake",
  table: "/table",
  plan: "/plan",
} as const;
